export const devoiceVoiceLanguages = [
  { code: "en-GB", label: "English (United Kingdom)" },
  { code: "en-US", label: "English (United States)" },
  { code: "en-AU", label: "English (Australia)" },
  { code: "en-CA", label: "English (Canada)" },
  { code: "en-IN", label: "English (India)" },
  { code: "en-IE", label: "English (Ireland)" },
  { code: "en-NZ", label: "English (New Zealand)" },
  { code: "en-ZA", label: "English (South Africa)" },
  { code: "zh-CN", label: "Chinese (Mandarin)" },
  { code: "zh-HK", label: "Chinese (Hong Kong)" },
  { code: "zh-TW", label: "Chinese (Taiwan)" },
  { code: "ar-AE", label: "Arabic (United Arab Emirates)" },
  { code: "ar-BH", label: "Arabic (Bahrain)" },
  { code: "ar-DZ", label: "Arabic (Algeria)" },
  { code: "ar-EG", label: "Arabic (Egypt)" },
  { code: "ar-IQ", label: "Arabic (Iraq)" },
  { code: "ar-JO", label: "Arabic (Jordan)" },
  { code: "ar-KW", label: "Arabic (Kuwait)" },
  { code: "ar-LB", label: "Arabic (Lebanon)" },
  { code: "ar-LY", label: "Arabic (Libya)" },
  { code: "ar-MA", label: "Arabic (Morocco)" },
  { code: "ar-OM", label: "Arabic (Oman)" },
  { code: "ar-QA", label: "Arabic (Qatar)" },
  { code: "ar-SA", label: "Arabic (Saudi Arabia)" },
  { code: "ar-SY", label: "Arabic (Syria)" },
  { code: "ar-TN", label: "Arabic (Tunisia)" },
  { code: "ar-YE", label: "Arabic (Yemen)" },
  { code: "bg-BG", label: "Bulgarian" },
  { code: "bn-BD", label: "Bengali (Bangladesh)" },
  { code: "bn-IN", label: "Bengali (India)" },
  { code: "ca-ES", label: "Catalan" },
  { code: "cs-CZ", label: "Czech" },
  { code: "da-DK", label: "Danish" },
  { code: "de-AT", label: "German (Austria)" },
  { code: "de-CH", label: "German (Switzerland)" },
  { code: "de-DE", label: "German (Germany)" },
  { code: "el-GR", label: "Greek" },
  { code: "es-ES", label: "Spanish" },
  { code: "es-AR", label: "Spanish (Argentina)" },
  { code: "es-BO", label: "Spanish (Bolivia)" },
  { code: "es-CL", label: "Spanish (Chile)" },
  { code: "es-CO", label: "Spanish (Colombia)" },
  { code: "es-CR", label: "Spanish (Costa Rica)" },
  { code: "es-CU", label: "Spanish (Cuba)" },
  { code: "es-DO", label: "Spanish (Dominican Republic)" },
  { code: "es-EC", label: "Spanish (Ecuador)" },
  { code: "es-GQ", label: "Spanish (Equatorial Guinea)" },
  { code: "es-GT", label: "Spanish (Guatemala)" },
  { code: "es-HN", label: "Spanish (Honduras)" },
  { code: "es-MX", label: "Spanish (Mexico)" },
  { code: "es-NI", label: "Spanish (Nicaragua)" },
  { code: "es-PA", label: "Spanish (Panama)" },
  { code: "es-PE", label: "Spanish (Peru)" },
  { code: "es-PR", label: "Spanish (Puerto Rico)" },
  { code: "es-PY", label: "Spanish (Paraguay)" },
  { code: "es-SV", label: "Spanish (El Salvador)" },
  { code: "es-US", label: "Spanish (United States)" },
  { code: "es-UY", label: "Spanish (Uruguay)" },
  { code: "es-VE", label: "Spanish (Venezuela)" },
  { code: "et-EE", label: "Estonian" },
  { code: "fa-IR", label: "Persian" },
  { code: "fi-FI", label: "Finnish" },
  { code: "fil-PH", label: "Filipino" },
  { code: "fr-BE", label: "French (Belgium)" },
  { code: "fr-CA", label: "French (Canada)" },
  { code: "fr-CH", label: "French (Switzerland)" },
  { code: "fr-FR", label: "French (France)" },
  { code: "ga-IE", label: "Irish" },
  { code: "gu-IN", label: "Gujarati" },
  { code: "he-IL", label: "Hebrew" },
  { code: "hi-IN", label: "Hindi" },
  { code: "hr-HR", label: "Croatian" },
  { code: "hu-HU", label: "Hungarian" },
  { code: "id-ID", label: "Indonesian" },
  { code: "is-IS", label: "Icelandic" },
  { code: "it-IT", label: "Italian" },
  { code: "ja-JP", label: "Japanese" },
  { code: "jv-ID", label: "Javanese" },
  { code: "kn-IN", label: "Kannada" },
  { code: "ko-KR", label: "Korean" },
  { code: "lt-LT", label: "Lithuanian" },
  { code: "lv-LV", label: "Latvian" },
  { code: "ml-IN", label: "Malayalam" },
  { code: "mr-IN", label: "Marathi" },
  { code: "ms-MY", label: "Malay" },
  { code: "nb-NO", label: "Norwegian Bokmal" },
  { code: "nl-BE", label: "Dutch (Belgium)" },
  { code: "nl-NL", label: "Dutch (Netherlands)" },
  { code: "pl-PL", label: "Polish" },
  { code: "pt-BR", label: "Portuguese (Brazil)" },
  { code: "pt-PT", label: "Portuguese (Portugal)" },
  { code: "ro-RO", label: "Romanian" },
  { code: "ru-RU", label: "Russian" },
  { code: "sk-SK", label: "Slovak" },
  { code: "sl-SI", label: "Slovenian" },
  { code: "sr-RS", label: "Serbian" },
  { code: "su-ID", label: "Sundanese" },
  { code: "sv-SE", label: "Swedish" },
  { code: "sw-KE", label: "Swahili (Kenya)" },
  { code: "sw-TZ", label: "Swahili (Tanzania)" },
  { code: "ta-IN", label: "Tamil (India)" },
  { code: "ta-LK", label: "Tamil (Sri Lanka)" },
  { code: "ta-MY", label: "Tamil (Malaysia)" },
  { code: "ta-SG", label: "Tamil (Singapore)" },
  { code: "te-IN", label: "Telugu" },
  { code: "th-TH", label: "Thai" },
  { code: "tr-TR", label: "Turkish" },
  { code: "uk-UA", label: "Ukrainian" },
  { code: "ur-IN", label: "Urdu (India)" },
  { code: "ur-PK", label: "Urdu (Pakistan)" },
  { code: "vi-VN", label: "Vietnamese" },
  { code: "zu-ZA", label: "Zulu" }
] as const;

export const devoiceVoices = [
  { id: "sonia", name: "1 - SoniaNeural", gender: "Woman", frequency: 440 },
  { id: "ryan", name: "2 - RyanNeural", gender: "Man", frequency: 196 },
  { id: "libby", name: "3 - LibbyNeural", gender: "Woman", frequency: 392 },
  { id: "abbi", name: "4 - AbbiNeural", gender: "Woman", frequency: 466 },
  { id: "ada", name: "5 - AdaMultilingualNeural", gender: "Woman", frequency: 523 },
  { id: "alfie", name: "6 - AlfieNeural", gender: "Man", frequency: 220 },
  { id: "bella", name: "7 - BellaNeural", gender: "Woman", frequency: 494 },
  { id: "elliot", name: "8 - ElliotNeural", gender: "Man", frequency: 247 },
  { id: "ethan", name: "9 - EthanNeural", gender: "Man", frequency: 294 },
  { id: "hollie", name: "10 - HollieNeural", gender: "Woman", frequency: 587 },
  { id: "maisie", name: "11 - MaisieNeural", gender: "Woman", frequency: 659 },
  { id: "noah", name: "12 - NoahNeural", gender: "Man", frequency: 175 },
  { id: "oliver", name: "13 - OliverNeural", gender: "Man", frequency: 262 },
  { id: "olivia", name: "14 - OliviaNeural", gender: "Woman", frequency: 554 },
  { id: "thomas", name: "15 - ThomasNeural", gender: "Man", frequency: 330 },
  { id: "ollie", name: "16 - OllieMultilingualNeural", gender: "Man", frequency: 311 }
] as const;

export type DeVoiceVoice = (typeof devoiceVoices)[number];

export function getVoiceLanguageLabel(code?: string | null) {
  return devoiceVoiceLanguages.find((language) => language.code === code)?.label ?? code ?? "English (United Kingdom)";
}

export function getVoiceLabel(id?: string | null) {
  if (id === "custom") return "Custom Voice";

  const voice = devoiceVoices.find((item) => item.id === id);
  return voice ? `${voice.name} ${voice.gender}` : id ?? "Custom Voice";
}
