export const devoiceVoiceLanguages = [
  { code: "target-afrikaans-south-africa", label: "Afrikaans (South Africa)" },
  { code: "target-albanian-albania", label: "Albanian (Albania)" },
  { code: "target-amharic-ethiopia", label: "Amharic (Ethiopia)" },
  { code: "ar-DZ", label: "Arabic (Algeria)" },
  { code: "ar-BH", label: "Arabic (Bahrain)" },
  { code: "ar-EG", label: "Arabic (Egypt)" },
  { code: "ar-IQ", label: "Arabic (Iraq)" },
  { code: "ar-JO", label: "Arabic (Jordan)" },
  { code: "ar-KW", label: "Arabic (Kuwait)" },
  { code: "ar-LB", label: "Arabic (Lebanon)" },
  { code: "ar-LY", label: "Arabic (Libya)" },
  { code: "ar-MA", label: "Arabic (Morocco)" },
  { code: "ar-OM", label: "Arabic (Oman)" },
  { code: "ar-QA", label: "Arabic (Qatar)" },
  { code: "ar-SA", label: "Arabic (Saudi Arabia)" },
  { code: "ar-SY", label: "Arabic (Syria)" },
  { code: "ar-TN", label: "Arabic (Tunisia)" },
  { code: "ar-AE", label: "Arabic (United Arab Emirates)" },
  { code: "ar-YE", label: "Arabic (Yemen)" },
  { code: "target-armenian-armenia", label: "Armenian (Armenia)" },
  { code: "target-assamese-india", label: "Assamese (India)" },
  { code: "target-azerbaijani-latin-azerbaijan", label: "Azerbaijani (Latin, Azerbaijan)" },
  { code: "target-basque", label: "Basque" },
  { code: "bn-BD", label: "Bengali (Bangladesh)" },
  { code: "bn-IN", label: "Bengali (India)" },
  { code: "target-bosnian-bosnia-and-herzegovina", label: "Bosnian (Bosnia and Herzegovina)" },
  { code: "target-bulgarian-bulgaria", label: "Bulgarian (Bulgaria)" },
  { code: "target-burmese-myanmar", label: "Burmese (Myanmar)" },
  { code: "ca-ES", label: "Catalan" },
  { code: "target-chinese-cantonese-simplified", label: "Chinese (Cantonese, Simplified)" },
  { code: "zh-HK", label: "Chinese (Cantonese, Traditional)" },
  { code: "target-chinese-central-plains-mandarin-henan-simplified", label: "Chinese (Central Plains Mandarin Henan, Simplified)" },
  { code: "target-chinese-central-plains-mandarin-shaanxi-simplified", label: "Chinese (Central Plains Mandarin Shaanxi, Simplified)" },
  { code: "target-chinese-guangxi-mandarin-simplified", label: "Chinese (Guangxi Mandarin, Simplified)" },
  { code: "target-chinese-jilu-mandarin-simplified", label: "Chinese (Jilu Mandarin, Simplified)" },
  { code: "zh-CN", label: "Chinese (Mandarin, Simplified)" },
  { code: "target-chinese-northeast-mandarin-simplified", label: "Chinese (Northeast Mandarin, Simplified)" },
  { code: "target-chinese-southwestern-mandarin-simplified", label: "Chinese (Southwestern Mandarin, Simplified)" },
  { code: "zh-TW", label: "Chinese (Taiwanese Mandarin, Traditional)" },
  { code: "target-chinese-wu-simplified", label: "Chinese (Wu, Simplified)" },
  { code: "hr-HR", label: "Croatian (Croatia)" },
  { code: "cs-CZ", label: "Czech (Czech Republic)" },
  { code: "da-DK", label: "Danish (Denmark)" },
  { code: "nl-BE", label: "Dutch (Belgium)" },
  { code: "nl-NL", label: "Dutch (Netherlands)" },
  { code: "en-AU", label: "English (Australia)" },
  { code: "en-CA", label: "English (Canada)" },
  { code: "target-english-hong-kong-sar", label: "English (Hong Kong SAR)" },
  { code: "en-IN", label: "English (India)" },
  { code: "en-IE", label: "English (Ireland)" },
  { code: "target-english-kenya", label: "English (Kenya)" },
  { code: "en-NZ", label: "English (New Zealand)" },
  { code: "target-english-nigeria", label: "English (Nigeria)" },
  { code: "target-english-philippines", label: "English (Philippines)" },
  { code: "target-english-singapore", label: "English (Singapore)" },
  { code: "en-ZA", label: "English (South Africa)" },
  { code: "target-english-tanzania", label: "English (Tanzania)" },
  { code: "en-GB", label: "English (United Kingdom)" },
  { code: "en-US", label: "English (United States)" },
  { code: "et-EE", label: "Estonian (Estonia)" },
  { code: "fil-PH", label: "Filipino (Philippines)" },
  { code: "fi-FI", label: "Finnish (Finland)" },
  { code: "fr-BE", label: "French (Belgium)" },
  { code: "fr-CA", label: "French (Canada)" },
  { code: "fr-FR", label: "French (France)" },
  { code: "fr-CH", label: "French (Switzerland)" },
  { code: "target-galician", label: "Galician" },
  { code: "target-georgian-georgia", label: "Georgian (Georgia)" },
  { code: "de-AT", label: "German (Austria)" },
  { code: "de-DE", label: "German (Germany)" },
  { code: "de-CH", label: "German (Switzerland)" },
  { code: "el-GR", label: "Greek (Greece)" },
  { code: "gu-IN", label: "Gujarati (India)" },
  { code: "he-IL", label: "Hebrew (Israel)" },
  { code: "hi-IN", label: "Hindi (India)" },
  { code: "hu-HU", label: "Hungarian" },
  { code: "is-IS", label: "Icelandic" },
  { code: "id-ID", label: "Indonesian" },
  { code: "ga-IE", label: "Irish (Ireland)" },
  { code: "it-IT", label: "Italian (Italy)" },
  { code: "ja-JP", label: "Japanese (Japan)" },
  { code: "jv-ID", label: "Javanese" },
  { code: "kn-IN", label: "Kannada (India)" },
  { code: "target-kazakh-kazakhstan", label: "Kazakh (Kazakhstan)" },
  { code: "target-khmer", label: "Khmer" },
  { code: "ko-KR", label: "Korean (South Korea)" },
  { code: "target-lao-laos", label: "Lao (Laos)" },
  { code: "lv-LV", label: "Latvian (Latvia)" },
  { code: "lt-LT", label: "Lithuanian (Lithuania)" },
  { code: "target-macedonian-north-macedonia", label: "Macedonian (North Macedonia)" },
  { code: "ms-MY", label: "Malay (Malaysia)" },
  { code: "ml-IN", label: "Malayalam (India)" },
  { code: "target-maltese-malta", label: "Maltese (Malta)" },
  { code: "mr-IN", label: "Marathi (India)" },
  { code: "target-mongolian-mongolia", label: "Mongolian (Mongolia)" },
  { code: "target-nepali-nepal", label: "Nepali (Nepal)" },
  { code: "nb-NO", label: "Norwegian Bokmål (Norway)" },
  { code: "target-odia-india", label: "Odia (India)" },
  { code: "target-pashto-afghanistan", label: "Pashto (Afghanistan)" },
  { code: "fa-IR", label: "Persian (Iran)" },
  { code: "pl-PL", label: "Polish (Poland)" },
  { code: "pt-BR", label: "Portuguese (Brazil)" },
  { code: "pt-PT", label: "Portuguese (Portugal)" },
  { code: "target-punjabi-india", label: "Punjabi (India)" },
  { code: "ro-RO", label: "Romanian (Romania)" },
  { code: "ru-RU", label: "Russian (Russia)" },
  { code: "target-serbian-cyrillic-serbia", label: "Serbian (Cyrillic, Serbia)" },
  { code: "target-serbian-latin-republic-of-serbia", label: "Serbian (Latin, Republic of Serbia)" },
  { code: "target-sinhala-sri-lanka", label: "Sinhala (Sri Lanka)" },
  { code: "sk-SK", label: "Slovak (Slovakia)" },
  { code: "sl-SI", label: "Slovenian (Slovenia)" },
  { code: "target-somali-somalia", label: "Somali (Somalia)" },
  { code: "es-AR", label: "Spanish (Argentina)" },
  { code: "es-BO", label: "Spanish (Bolivia)" },
  { code: "es-CL", label: "Spanish (Chile)" },
  { code: "es-CO", label: "Spanish (Colombia)" },
  { code: "es-CR", label: "Spanish (Costa Rica)" },
  { code: "es-CU", label: "Spanish (Cuba)" },
  { code: "es-DO", label: "Spanish (Dominican Republic)" },
  { code: "es-EC", label: "Spanish (Ecuador)" },
  { code: "es-SV", label: "Spanish (El Salvador)" },
  { code: "es-GQ", label: "Spanish (Equatorial Guinea)" },
  { code: "es-GT", label: "Spanish (Guatemala)" },
  { code: "es-HN", label: "Spanish (Honduras)" },
  { code: "es-MX", label: "Spanish (Mexico)" },
  { code: "es-NI", label: "Spanish (Nicaragua)" },
  { code: "es-PA", label: "Spanish (Panama)" },
  { code: "es-PY", label: "Spanish (Paraguay)" },
  { code: "es-PE", label: "Spanish (Peru)" },
  { code: "es-PR", label: "Spanish (Puerto Rico)" },
  { code: "es-ES", label: "Spanish (Spain)" },
  { code: "es-US", label: "Spanish (United States)" },
  { code: "es-UY", label: "Spanish (Uruguay)" },
  { code: "es-VE", label: "Spanish (Venezuela)" },
  { code: "target-sundanese-indonesia", label: "Sundanese (Indonesia)" },
  { code: "sw-KE", label: "Swahili (Kenya)" },
  { code: "sw-TZ", label: "Swahili (Tanzania)" },
  { code: "sv-SE", label: "Swedish (Sweden)" },
  { code: "ta-IN", label: "Tamil (India)" },
  { code: "ta-MY", label: "Tamil (Malaysia)" },
  { code: "ta-SG", label: "Tamil (Singapore)" },
  { code: "ta-LK", label: "Tamil (Sri Lanka)" },
  { code: "te-IN", label: "Telugu (India)" },
  { code: "th-TH", label: "Thai (Thailand)" },
  { code: "tr-TR", label: "Turkish (Turkey)" },
  { code: "uk-UA", label: "Ukrainian (Ukraine)" },
  { code: "ur-IN", label: "Urdu (India)" },
  { code: "ur-PK", label: "Urdu (Pakistan)" },
  { code: "target-uzbek-latin-uzbekistan", label: "Uzbek (Latin, Uzbekistan)" },
  { code: "vi-VN", label: "Vietnamese (Vietnam)" },
  { code: "target-welsh-united-kingdom", label: "Welsh (United Kingdom)" },
  { code: "zu-ZA", label: "Zulu (South Africa)" }
] as const;

export const devoiceVoices = [
  { id: "sonia", name: "1 - SoniaNeural", gender: "Woman", frequency: 440 },
  { id: "ryan", name: "2 - RyanNeural", gender: "Man", frequency: 196 },
  { id: "libby", name: "3 - LibbyNeural", gender: "Woman", frequency: 392 },
  { id: "abbi", name: "4 - AbbiNeural", gender: "Woman", frequency: 466 },
  { id: "ada", name: "5 - AdaMultilingualNeural", gender: "Woman", frequency: 523 },
  { id: "alfie", name: "6 - AlfieNeural", gender: "Man", frequency: 220 },
  { id: "bella", name: "7 - BellaNeural", gender: "Woman", frequency: 494 },
  { id: "elliot", name: "8 - ElliotNeural", gender: "Man", frequency: 247 },
  { id: "ethan", name: "9 - EthanNeural", gender: "Man", frequency: 294 },
  { id: "hollie", name: "10 - HollieNeural", gender: "Woman", frequency: 587 },
  { id: "maisie", name: "11 - MaisieNeural", gender: "Woman", frequency: 659 },
  { id: "noah", name: "12 - NoahNeural", gender: "Man", frequency: 175 },
  { id: "oliver", name: "13 - OliverNeural", gender: "Man", frequency: 262 },
  { id: "olivia", name: "14 - OliviaNeural", gender: "Woman", frequency: 554 },
  { id: "thomas", name: "15 - ThomasNeural", gender: "Man", frequency: 330 },
  { id: "ollie", name: "16 - OllieMultilingualNeural", gender: "Man", frequency: 311 }
] as const;

export type DeVoiceVoice = (typeof devoiceVoices)[number];

export function getVoiceLanguageLabel(code?: string | null) {
  return devoiceVoiceLanguages.find((language) => language.code === code)?.label ?? code ?? "English (United Kingdom)";
}

export function getVoiceLabel(id?: string | null) {
  if (id === "custom") return "Custom Voice";

  const voice = devoiceVoices.find((item) => item.id === id);
  return voice ? `${voice.name} ${voice.gender}` : id ?? "Custom Voice";
}
